@echo off
rd /s /q "C:\Users\guilh\OneDrive\Documentos\GitHub\ra_fauna\.vscode"
rd /s /q "C:\Users\guilh\OneDrive\Documentos\GitHub\ra_fauna\Library"
rd /s /q "C:\Users\guilh\OneDrive\Documentos\GitHub\ra_fauna\Logs"
rd /s /q "C:\Users\guilh\OneDrive\Documentos\GitHub\ra_fauna\Temp"
rd /s /q "C:\Users\guilh\OneDrive\Documentos\GitHub\ra_fauna\UserSettings"
del /s /q "C:\Users\guilh\OneDrive\Documentos\GitHub\ra_fauna\Assembly-CSharp.csproj"
del /s /q "C:\Users\guilh\OneDrive\Documentos\GitHub\ra_fauna\Assembly-CSharp-Editor.csproj"
del /s /q "C:\Users\guilh\OneDrive\Documentos\GitHub\ra_fauna\Assembly-CSharp-Editor-firstpass.csproj"
del /s /q "C:\Users\guilh\OneDrive\Documentos\GitHub\ra_fauna\Assembly-CSharp-firstpass.csproj"
del /s /q "C:\Users\guilh\OneDrive\Documentos\GitHub\ra_fauna\ra_fauna.sln"